import * as React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head'
import Image from 'next/image'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { useTranslation } from 'next-i18next';

import Container from '@mui/material/Container';
import Typography from '@mui/material/Typography';
import Box from '@mui/material/Box';

import client from "@/config/apollo";
import { COUNTRIES } from "@/data/queries/countries"

const Home: NextPage = () => {
  const { t } = useTranslation(['common']);
  return (
    <Container maxWidth='lg'>
      <Head>
        <title>Next App Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Box
        sx={{
          my: 5,
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'center',
          alignItems: 'center',
        }}
      >
        <Typography component='h1' color='primary'>
          Boilerplate for building faster. Only SSR.
        </Typography>
        <Typography component='h2' color='secondary'>
          Material UI v5 with Next.js in TypeScript
        </Typography>
        <Typography component='h2' color='secondary'>
          Sentry/Next for error handling
        </Typography>
        <Typography component='h2' color='secondary'>
          Apollo Client for data fetching
        </Typography>
        <Typography component='h2' color='secondary'>
          {t('common:hello')}
        </Typography>

        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
      </Box>
    </Container>
  );
};

export async function getServerSideProps({ locale }: { locale: string}) {
  const { data } = await client.query({
    query: COUNTRIES,
  });

  return {
    props: {
      ...(await serverSideTranslations(locale, ['common'])),
      // Will be passed to the page component as props
      countries: data.countries.slice(0, 4),
    },
  };
}

export default Home;